In [4]:
import pandas as pd
df = pd.read_csv('nfl_fans.csv')

In [5]:
df.head()

,Unnamed: 0,Democrat,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Independent,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,NaN,Team,Tot. Respondents,Asian,Black,Hispanic,Other,White,Total,Asian,...,Black,Hispanic,Other,White,Total,GOP%,Dem%,Ind%,White%,Nonwhite%
1,NaN,Arizona Cardinals,148,2,7,7,3,20,39,4,...,1,5,2,30,38,26%,26%,48%,68%,32%
2,NaN,Atlanta Falcons,188,3,27,5,1,23,59,3,...,7,2,3,41,54,29%,31%,40%,57%,43%
3,NaN,Baltimore Ravens,150,5,14,3,4,30,56,3,...,1,1,1,26,29,19%,37%,43%,68%,32%
4,NaN,Buffalo Bills,92,2,3,1,1,15,22,7,...,3,4,NaN,16,24,26%,24%,50%,67%,33%